### ISSUE TITLE
how to connect to websocket?

### ISSUE THREAD

**Issue by SimonVillage** [qyvlik/viabtc_exchange_server_docker#4]
Is there any way to connect to websocket from remote?

**Comment by SimonVillage** [comment]
tweaked `docker-compose.yml`

```
services:
  btc:
    privileged: true
    container_name: btc-service
    build: ./btc/
    volumes:
     - /tmp/accessws:/tmp:rw
```

and added this nginx config

```
server {
  listen 8008;

  location / {
    proxy_pass http://unix:/tmp/accessws/accessws.sock;
    # proxy_pass http://127.0.0.1:18091;
    proxy_redirect off;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_send_timeout 1d;
    proxy_read_timeout 1d;
    proxy_connect_timeout 1d;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
```
